const fs = require('fs');

const en = JSON.parse(fs.readFileSync('src/i18n/locales/en.json', 'utf8'));

en.creator_steps = {
    "step1Title": "Pool Type",
    "step2Title": "Identity",
    "step3Title": "Prizes and Rules",
    "step4Title": "Community",
    "step5Title": "Payment Registration",
    "step6Title": "Ready!",
    "stepOf": "Step {step} of {total}",
    "back": "Back",
    "continue": "Continue",
    "validating": "Validating...",
    "processing": "Processing...",
    "typeLabel": "Pool Type",
    "typeAmigos": "Among Friends (Free)",
    "typeAmigosDesc": "Small and family groups (up to 20 participants)",
    "typePrivada": "Private (Promoters)",
    "typePrivadaDesc": "For promoters and influencers (up to 1,000 participants)",
    "typeComercial": "Commercial On-site",
    "typeComercialDesc": "Anchored to a physical venue",
    "typeNacional": "National Digital",
    "typeNacionalDesc": "Visible nationwide",
    "logoLabel": "Pool Logo or Photo",
    "nameLabel": "Pool Name *",
    "namePlaceholderNacional": "Ex: National Mega Promo",
    "namePlaceholderDefault": "Ex: Store X Pool",
    "idLabel": "Identification *",
    "idPlaceholder": "Ex: ID, Plate, Apt, etc",
    "cityLabel": "City / Location",
    "cityPlaceholder": "Ex: Miami, Brickell",
    "addressLabel": "Detailed Address",
    "addressPlaceholder": "Street, Mall, Store...",
    "locationCaptured": "Location Captured ✓",
    "captureGPS": "Capture GPS Coordinates",
    "nationalReach": "National Reach Active",
    "nationalReachDesc": "This pool will be visible throughout {pais}.",
    "prizesLabel": "Available Prizes",
    "prizesPh": "Ex: Dinner for 2, 50% Discount...",
    "additionalImagesLabel": "Additional Images (Sponsors / Gallery)",
    "additionalImagesHint": "Ideal for sponsor logos or venue photos.",
    "requirementsLabel": "Redemption Requirements",
    "requirementsPh": "Ex: Show purchase receipt, Follow us on social media...",
    "minAgeLabel": "Minimum Age",
    "age13": "13+ years",
    "age18": "18+ years (Legal)",
    "age21": "21+ years",
    "communityChannels": "Communication Channels",
    "communityChannelsDesc": "Where you will publish rankings and winners.",
    "paymentTitle": "Payment Registration and Activation",
    "paymentDesc": "Complete the payment details to activate your pool.",
    "amountLabel": "Amount to Register",
    "sobresEquiv": "Equivalent to {n} Panini Envelopes",
    "free": "FREE",
    "freeAmigos": "Among Friends Pool (No Cost)",
    "guestOverlayTitle": "GUEST / DEMO MODE",
    "guestOverlayDesc": "You are browsing as a guest. Changes will not be saved permanently. Register to get full access.",
    "trialPermit": "⚡ TRIAL PERMIT ACTIVE",
    "trialPermitDesc": "You can register and test up to 10 pools with real data completely free. Payment will be validated before the World Cup starts.",
    "bankLabel": "Bank / Payment Method",
    "bankDefault": "Select a bank or method",
    "bankPagoMovil": "Mobile Payment",
    "bankTransferencia": "Bank Transfer",
    "bankZelle": "Zelle / Paypal",
    "bankEfectivo": "Cash / Custody",
    "referenceLabel": "Reference Number",
    "referencePh": "Ex: 12345678",
    "dateLabel": "Payment Date",
    "freeNoPayment": "Your free plan does not require any payment data!",
    "freeClickBelow": "Click the button below to activate your pool instantly.",
    "minRequired": "Remember that the minimum number of participants must be 10 to validate your pool.",
    "hoursReminder": "Remember that friends have 48 hours to register or the right to the pool will be automatically lost.",
    "exclusiveFeature": "Exclusive Feature for Registered Promoters",
    "exclusiveFeatureDesc": "To register payment and activate your pool permanently, you must complete your free registration on the platform.",
    "registerNow": "Register now",
    "accessCode": "Access Code",
    "quinielaCreated": "Pool Created!",
    "requestSent": "Request Sent",
    "createFree": "Create Free Pool",
    "createAndPay": "Create Pool and Register Payment",
    "downloadAccept": "I have downloaded and accept that my request is subject to approval.",
    "unlockMenu": "⚠️ ACTIVATE TO UNLOCK MENU",
    "goToPromoterMenu": "Go to Promoter Menu",
    "errSelectType": "Select a pool type",
    "errAmigosLimit": "You already have an \"Among Friends\" Pool active. The free plan is limited to one pool per user.",
    "errNacional": "You are not authorized to create national pools",
    "errNameRequired": "Name is required",
    "errLogoRequired": "Pool logo is required",
    "errIdRequired": "You must specify what identification you will ask for (ex. Apt, Member, etc.)",
    "errAddressRequired": "Commercial pools require City and Address",
    "errGeoNotSupported": "Geolocation is not supported by this browser",
    "errGeoFailed": "Location could not be captured. Make sure to grant permissions."
};

en.plans_promoter = {
    "title": "ACTIVATE YOUR POOL HERE",
    "whyNeverLate": "Why is it never too late to start your among friends or commercial pool?",
    "freePlan": "Among Friends",
    "freeSubtitle": "Small groups",
    "freePrice": "FREE",
    "freeF1": "Minimum 10 participants",
    "freeF2": "Maximum 20 participants",
    "freeF3": "48 hours to meet minimum",
    "freeF4": "Limit of 1 creation per user",
    "privatePlan": "Private",
    "privateSubtitle": "Friends and Influencers",
    "privateF1": "Limit: 1,000 participants",
    "privateF2": "Up to 3,000 forms",
    "privateF3": "Autonomous prize management",
    "privateF4": "Standard support",
    "comercialPlan": "Commercial",
    "comercialSubtitle": "Businesses and Brands",
    "comercialF1": "Limit: 10,000 participants",
    "comercialF2": "Up to 30,000 forms",
    "comercialF3": "Metaverse Branding (Logo)",
    "comercialF4": "Arts Kits (Postcards, Pro Frames)",
    "comercialF5": "1 Free Private Pool",
    "comercialF6": "Activate VAR BINGO promotions for each match",
    "comercialF7": "Activate WORLD CUP CYCLONE promotional draws for each match",
    "mostProfitable": "⭐ MOST PROFITABLE",
    "nationalPlan": "National",
    "nationalSubtitle": "Large Events",
    "nationalPrice": "UPON REQUEST",
    "nationalF1": "Unlimited participants",
    "nationalF2": "24/7 dedicated support",
    "nationalF3": "Total immersive branding",
    "nationalF4": "Media integration",
    "envelopes": "ENVELOPES",
    "albums": "ALBUMS",
    "paniniEnvelopes": "Panini Envelopes",
    "paniniAlbums": "Full Panini Albums",
    "operativeCost": "Operational cost: ~$",
    "usd": "USD",
    "btnConsult": "CONSULT",
    "btnPrivate": "Start your Private Pool",
    "btnFree": "Create your Among Friends Pool",
    "btnComercial": "Start your Commercial Pool",
    "costInCountry1": "Cost of Envelopes in ",
    "costInCountry2": "your country",
    "disclaimer": "* The operational cost is calculated based on the local value of the sticker envelope. A full album is equivalent to 50 envelopes in our conversion index.",
    "cromosIndex": "Sticker Index",
    "modalText1": "Unlike traditional pools that force you to start in the first second of the tournament, in the ",
    "modalBrand": "Best Digital Interactive FanFest",
    "modalText2": " you can join and compete at any time.",
    "modalText3": "Previously played matches are automatically scored as 0 points, maintaining the advantage for players who registered early with less information. But with 48 teams and dozens of matches ahead, you have plenty of opportunities to catch up, have fun and win exclusive draws every matchday!",
    "understood": "Understood"
};

fs.writeFileSync('src/i18n/locales/en.json', JSON.stringify(en, null, 2));
console.log('en.json translated');
